export const LEGAL_CONTENT: Record<string, { title: string; html: string }> = {
  faq: {
    title: 'Frequently Asked Questions',
    html: `
<div class="mkt-faq-cat">Getting Started</div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How does Mathbord work?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Mathbord follows a structured five\u2011step process. It starts with a free 3\u2011minute consultation where we learn about your goals, academic level, and timeline. From there, we review the student\u2019s profile, match them with a vetted specialist tutor, build a personalized lesson plan, and track progress with visible milestones.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">Who is Mathbord for?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Mathbord serves students at every level \u2014 from elementary math through university calculus and standardized test prep (SAT, GRE, GMAT). We work with families looking for reliable academic support, students who need structured gap recovery, and learners preparing for high\u2011stakes exams. Our tutors cover all major Canadian provincial curricula, IB, and AP programs.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How do I get started?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Book a free 3\u2011minute consultation through our website. We\u2019ll discuss the student\u2019s current situation, goals, and timeline. Within 24\u201348 hours, we\u2019ll match you with a specialist tutor and share a proposed lesson plan. There\u2019s no commitment required.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">Is Mathbord available across Canada?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Yes. All tutoring is delivered online, so we serve students in every province and territory. Our tutors are experienced with Ontario, British Columbia, Alberta, Quebec, and other provincial curricula, as well as IB and AP.</div></div></div>
<div class="mkt-faq-cat">Tutors & Quality</div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How are Mathbord tutors vetted?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Every tutor goes through a rigorous selection process. We verify academic credentials (minimum undergraduate degree in a quantitative field), assess subject expertise through a technical interview, evaluate teaching ability with a mock lesson, and check references.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">Can I request a specific tutor or switch tutors?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Absolutely. We carefully match tutors based on the student\u2019s subject, level, learning style, and schedule. If for any reason the fit isn\u2019t right, you can request a new match at no cost.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">What subjects and levels do you cover?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">We specialize exclusively in mathematics: elementary math, middle school foundations, high school functions, trigonometry, and calculus (across all provincial curricula), IB Math AA and AI, AP Calculus AB and BC, university\u2011level calculus, linear algebra, statistics, and standardized test prep (SAT, PSAT, GRE Quant, GMAT Quant).</div></div></div>
<div class="mkt-faq-cat">Pricing & Billing</div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How much does tutoring cost?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Typical rates range from $45\u2013$70 per hour for one\u2011on\u2011one sessions. We provide a clear quote after your consultation \u2014 no hidden fees, no contracts. Group sessions and bootcamps are available at reduced per\u2011student rates.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How does billing work?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">We invoice bi\u2011weekly based on completed lessons. You\u2019ll receive a detailed invoice by email with a secure online payment link. We accept all major credit cards and bank transfers. There are no upfront packages required \u2014 you pay only for sessions completed.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">Is there a minimum commitment?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">No. There are no long\u2011term contracts or minimum session commitments. We recommend consistency for the best results (typically 1\u20132 sessions per week), but you can adjust, pause, or stop at any time.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">What is your cancellation policy?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Lessons cancelled with at least 24 hours\u2019 notice incur no charge. Cancellations with less than 24 hours\u2019 notice may be charged at 50% of the session rate. No\u2011shows are billed at the full session rate.</div></div></div>
<div class="mkt-faq-cat">Sessions & Technology</div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How are lessons delivered?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">All lessons take place online through Lessonspace, a virtual classroom purpose\u2011built for tutoring. It includes video, audio, a collaborative infinite whiteboard with math\u2011specific tools, screen sharing, and file sharing. There\u2019s nothing to download \u2014 students just click their unique Lessonspace link.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">What technology do I need?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">A computer or tablet with a stable internet connection, a webcam, and a microphone. Lessonspace runs in your browser (Chrome recommended) with no downloads required. A stylus or drawing tablet is helpful but not required.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How do I track my child\u2019s progress?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Every client has access to a dashboard with upcoming sessions, lesson reports written by the tutor, progress charts tracking improvement over time, and milestone achievements. You\u2019ll always know exactly where your child stands.</div></div></div>
<div class="mkt-faq-cat">For Tutors</div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How do I apply to become a Mathbord tutor?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Visit the \u201CTeach with Us\u201D section on our website and complete the application form. We review every application within 48 hours. If your profile is a fit, we\u2019ll schedule a technical interview and mock teaching session.</div></div></div>
<div class="mkt-faq-item"><div class="mkt-faq-q">How much do tutors earn?</div><div class="mkt-faq-a"><div class="mkt-faq-a-inner">Tutor pay ranges from $40\u2013$65 per hour. Payouts are processed bi\u2011weekly via direct deposit. We handle all client billing, scheduling, and administration \u2014 tutors focus entirely on teaching.</div></div></div>`
  },
  privacy: {
    title: 'Privacy Policy',
    html: `<p style="font-size:0.78rem;color:var(--mkt-gray-400);margin-bottom:1.5rem">Effective: February 1, 2026 \u00b7 Last updated: February 27, 2026</p>
<h3>1. Introduction</h3><p>Mathbord (\u201Cwe,\u201D \u201Cus,\u201D or \u201Cour\u201D) operates the Mathbord platform, including our website and related services. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use our Service.</p>
<h3>2. Information We Collect</h3><p><strong>Information you provide:</strong> account information (name, email, phone, password), student profiles, tutor applications, consultation forms, payment information (processed by Stripe), and platform communications.</p><p><strong>Automatically collected:</strong> usage data, device information, log data (IP, access times), and cookies for authentication and analytics.</p>
<h3>3. How We Use Your Information</h3><p>We use information to provide the Service, process payments, communicate about accounts and sessions, match students with tutors, generate progress reports, evaluate tutor applications, improve the Service, and comply with legal obligations.</p>
<h3>4. How We Share Your Information</h3><p>We do not sell your personal information. We share data between platform participants as needed (tutors see relevant student info), with service providers (Lessonspace, Stripe, hosting, analytics), when required by law, and in connection with business transfers.</p>
<h3>5. Children\u2019s Privacy</h3><p>We collect student information only through their parent or guardian\u2019s account and with parental consent. Parents may review, update, or request deletion of their child\u2019s information at <a href="mailto:privacy@mathbord.com">privacy@mathbord.com</a>.</p>
<h3>6. Data Security</h3><p>We implement industry\u2011standard security measures including encryption (TLS/SSL), secure authentication, regular security assessments, and access controls.</p>
<h3>7. Data Retention</h3><p>We retain information for as long as your account is active. After closure, data is retained up to 24 months for legal purposes, then securely deleted or anonymized.</p>
<h3>8. Your Rights</h3><p>You may access, correct, delete, restrict, or export your personal information. Contact <a href="mailto:privacy@mathbord.com">privacy@mathbord.com</a> and we will respond within 30 days.</p>
<h3>9. Canadian Privacy Law</h3><p>Mathbord complies with PIPEDA and applicable provincial privacy legislation.</p>
<h3>10. Cookies</h3><p>We use essential cookies (authentication, security) and analytics cookies. We do not use advertising or third\u2011party tracking cookies.</p>
<h3>11. Changes</h3><p>We may update this policy. Material changes will be posted on the Service with an updated date.</p>
<h3>12. Contact</h3><div class="mkt-legal-callout"><p><strong>Mathbord Privacy Team</strong><br>Email: <a href="mailto:privacy@mathbord.com">privacy@mathbord.com</a><br>Location: Vancouver, BC, Canada</p></div>`
  },
  terms: {
    title: 'Terms of Service',
    html: `<p style="font-size:0.78rem;color:var(--mkt-gray-400);margin-bottom:1.5rem">Effective: February 1, 2026 \u00b7 Last updated: February 27, 2026</p>
<h3>1. Acceptance of Terms</h3><p>By accessing or using the Mathbord platform, you agree to be bound by these Terms. If using on behalf of a minor, you represent that you are the parent or legal guardian.</p>
<h3>2. Description of Service</h3><p>Mathbord connects students with vetted math tutors for personalized instruction. The Service includes tutor matching, scheduling, virtual classroom sessions powered by Lessonspace, progress tracking, and invoicing. Tutors are independent contractors, not Mathbord employees.</p>
<h3>3. Accounts</h3><p>You must provide accurate information, keep credentials confidential, and accept responsibility for all account activity. We may suspend accounts that violate these Terms.</p>
<h3>4. Client Terms</h3><p><strong>Cancellation:</strong> 24+ hours\u2019 notice = no charge. Less than 24 hours = 50% charge. No-shows = full charge.</p><p><strong>Payment:</strong> Invoices issued bi\u2011weekly, due within 14 days. Late payments may incur 1.5%/month. Services may be suspended for balances over 30 days.</p><p><strong>Satisfaction:</strong> Contact us within 7 days of first session for a free replacement match.</p>
<h3>5. Tutor Terms</h3><p>Tutors are independent contractors responsible for their own taxes. Compensation is per agreed rate, paid bi\u2011weekly. During engagement and 12 months following, tutors may not solicit Mathbord clients outside the platform.</p>
<h3>6. Acceptable Use</h3><p>Do not use the Service unlawfully, provide false information, harass others, attempt unauthorized access, or circumvent the platform to avoid fees.</p>
<h3>7. Intellectual Property</h3><p>The Service and its content are owned by Mathbord. Lesson materials remain the property of their creators. Lesson reports are jointly accessible.</p>
<h3>8. Virtual Classroom</h3><p>Lessons are conducted through Lessonspace. By using the Service, you agree to Lessonspace\u2019s terms. Sessions may be recorded for quality assurance with prior notice. Do not record or share session content without all parties\u2019 consent.</p>
<h3>9. Limitation of Liability</h3><p>Mathbord is not liable for indirect or consequential damages. Total liability shall not exceed fees paid in the 12 months preceding a claim.</p><div class="mkt-legal-callout"><p>Mathbord does not guarantee specific academic outcomes, grades, or test scores. Results depend on student effort, consistency, and preparation.</p></div>
<h3>10. Indemnification</h3><p>You agree to indemnify Mathbord from claims arising from your use of the Service or violation of these Terms.</p>
<h3>11. Dispute Resolution</h3><p>Disputes shall first be addressed through good\u2011faith negotiation, then binding arbitration in Vancouver, BC. These Terms are governed by the laws of British Columbia, Canada.</p>
<h3>12. Modifications</h3><p>We may modify these Terms at any time with notice. Continued use constitutes acceptance.</p>
<h3>13. Termination</h3><p>Either party may terminate at any time. Outstanding invoices remain due. We may immediately terminate access for violations.</p>
<h3>14. Contact</h3><div class="mkt-legal-callout"><p><strong>Mathbord Legal</strong><br>Email: <a href="mailto:legal@mathbord.com">legal@mathbord.com</a><br>Location: Vancouver, BC, Canada</p></div>`
  }
};
